apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-microservice
  namespace: ms1
spec:
  replicas: 3
  strategy:
    type: Recreate  # Specify the strategy as Recreate
  selector:
    matchLabels:
      app: nest-microservice
  template:
    metadata:
      labels:
        app: nest-microservice
    spec:
      containers:
      - name: nest-microservice
        image: alisoufnet/nest_microservice:1.1.1
        ports:
        - containerPort: 3000
