apiVersion: v1
kind: Service
metadata:
  name: nest-microservice
  namespace: ms1  # Specify the same namespace as your deployment
spec:
  selector:
    app: nest-microservice  # Selector to match the labels of your deployment pods
  ports:
    - protocol: TCP
      port: 3080   # Port that the service will listen on
      targetPort: 3000  # Port that the pods are listening on
  type: NodePort  # Expose the service on a port on each node
