name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test Nest Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js and dependencies
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get project version from package.json
        id: version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PW }}

      - name: Build Docker image
        run: |
          DOCKER_TAG="${{ secrets.DOCKERHUB_USERNAME }}/nest_microservice:${{ steps.version.outputs.version }}"
          docker build -t $DOCKER_TAG .
        #run: docker build -t alisoufnet/nest_microsercice:latest .

      - name: Push Docker image to Docker Hub
        run: docker push $DOCKER_TAG
        #run: docker push alisoufnet/nest_microsercice:latest

